filegroup(
    name = "example_class",
    srcs = [
        "example_class.cls",
        "@bazel_latex_texlive//:texlive_texmf__texmf-dist__tex__latex__xcolor",
    ],
    visibility = ["//visibility:public"],
)
