name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  buildifier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: thompsonja/bazel-buildifier@v0.4.0
        with:
          buildifier_version: 5.1.0
          warnings: all

  test:
    strategy:
      matrix:
        folder:
          - "example"
          - "packages"
        platform:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
      - name: Mount bazel caches
        id: bazel_cache
        uses: actions/cache@v3
        with:
          path: |
            "~/.cache/bazel"
            "~/.cache/bazel-repo"
          key: ${{matrix.platform}}-bazel-cache-${{ hashFiles('**/BUILD.bazel', '**/*.bzl', 'WORKSPACE') }}
          restore-keys: ${{matrix.platform}}-bazel-cache-
      - name: Build ${{ matrix.folder }}
        env:
          XDG_CACHE_HOME: ~/.cache/bazel-repo
        run: |
          bazel build //${{ matrix.folder }}:all
      - name: Test
        if: ${{matrix.folder == 'example'}}
        env:
          XDG_CACHE_HOME: ~/.cache/bazel-repo
        run: |
          bazel test //${{ matrix.folder }}/test/... --verbose_failures --test_output=streamed
